### ISSUE TITLE
options support 

### ISSUE THREAD

**Issue by wwwaiser** [serbanghita/jQM-dynamic-popup#1]
It would be great provide opportunity to pass more settings to the popup.
for example creating popup with different themes

**Comment by serbanghita** [comment]
@wice24 agree, can you provide a test case. How exactly are you using the popup?

**Comment by wwwaiser** [comment]
my use case is very simple, i just generate content for popup and showing it, but i have different themes in application and you support only `'data-theme': 'b'`

**Comment by serbanghita** [comment]
The new release covers a lot of options. Check the new `README` on the front page.
